{
  /* IP */
}
export const IP_REQUEST_SUCCESS = "IP_REQUEST_SUCCESS";
export const IP_REQUEST_PENDING = "IP_REQUEST_PENDING";
export const IP_REQUEST_FAILED = "IP_REQUEST_FAILED";
{
  /*CATEGORY */
}
export const CATEGORY_REQUEST_SUCCESS = "CATEGORY_REQUEST_SUCCESS";
export const CATEGORY_REQUEST_PENDING = "CATEGORY_REQUEST_PENDING";
export const CATEGORY_REQUEST_FAILED = "CATEGORY_REQUEST_FAILED";
{
  /*PRODUCTS */
}
export const PRODUCT_REQUEST_SUCCESS = "PRODUCT_REQUEST_SUCCESS";
export const PRODUCT_REQUEST_PENDING = "PRODUCT_REQUEST_PENDING";
export const PRODUCT_REQUEST_FAILED = "PRODUCT_REQUEST_FAILED";

{
  /*Landing */
}
export const LANDING_REQUEST_SUCCESS = "LANDING_REQUEST_SUCCESS";
export const LANDING_REQUEST_PENDING = "LANDING_REQUEST_PENDING";
export const LANDING_REQUEST_FAILED = "LANDING_REQUEST_FAILED";
{
  /*RECENTLY_VIEWED*/
}
export const RECENTLY_VIEWED_REQUEST_SUCCESS =
  "RECENTLY_VIEWED_REQUEST_SUCCESS";
export const RECENTLY_VIEWED_REQUEST_PENDING =
  "RECENTLY_VIEWED_REQUEST_PENDING";
export const RECENTLY_VIEWED_REQUEST_FAILED = "RECENTLY_VIEWED_REQUEST_FAILED";
{
  /* WISHLIST */
}
export const WISHLIST_REQUEST_SUCCESS = "WISHLIST_REQUEST_SUCCESS";
export const WISHLIST_REQUEST_PENDING = "WISHLIST_REQUEST_PENDING";
export const WISHLIST_REQUEST_FAILED = "WISHLIST_REQUEST_FAILED";

/*Cart Items*/

export const CART_REQUEST_SUCCESS = "CART_REQUEST_SUCCESS";
export const CART_REQUEST_PENDING = "CART_REQUEST_PENDING";
export const CART_REQUEST_FAILED = "CART_REQUEST_FAILED";

export const GET_CART_REQUEST_SUCCESS = "GET_CART_REQUEST_SUCCESS";
export const GET_CART_REQUEST_PENDING = "GET_CART_REQUEST_PENDING";
export const GET_CART_REQUEST_FAILED = "GET_CART_REQUEST_FAILED";

export const REMOVE_CART_REQUEST_SUCCESS = "REMOVE_CART_REQUEST_SUCCESS";
export const REMOVE_CART_REQUEST_PENDING = "REMOVE_CART_REQUEST_PENDING";
export const REMOVE_CART_REQUEST_FAILED = "REMOVE_CART_REQUEST_FAILED";

///PAYMENT
export const PAYMENT_STATUS_REQUEST_SUCCESS = "PAYMENT_STATUS_REQUEST_SUCCESS";
export const PAYMENT_STATUS_REQUEST_PENDING = "PAYMENT_STATUS_REQUEST_PENDING";
export const PAYMENT_STATUS_REQUEST_FAILED = "PAYMENT_STATUS_REQUEST_FAILED";
//GET ORDER
export const GET_ORDER_DETAILS_SUCCESS = "GET_ORDER_DETAILS_SUCCESS";
export const GET_ORDER_DETAILS_PENDING = "GET_ORDER_DETAILS_PENDING";
export const GET_ORDER_DETAILS_FAILED = "GET_ORDER_DETAILS_FAILED";
//Refund Requests
export const GET_REFUND_BY_ORDER_NUMBER = "GET_REFUND_BY_ORDER_NUMBER";
export const GENERATE_NOTIFICATION_FOR_VENDOR_USER =
  "GENERATE_NOTIFICATION_FOR_VENDOR_USER";
